
package traffic.wcf.bss.com.bskyb.tsversion;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-12T12:37:20.968+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "BusinessException", targetNamespace = "http://BSkyB.com.BSS.Common")
public class ITSVersionGetBusinessExceptionFaultFaultMessage extends Exception {
    
    private common.bss.com.bskyb.BusinessException businessException;

    public ITSVersionGetBusinessExceptionFaultFaultMessage() {
        super();
    }
    
    public ITSVersionGetBusinessExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public ITSVersionGetBusinessExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ITSVersionGetBusinessExceptionFaultFaultMessage(String message, common.bss.com.bskyb.BusinessException businessException) {
        super(message);
        this.businessException = businessException;
    }

    public ITSVersionGetBusinessExceptionFaultFaultMessage(String message, common.bss.com.bskyb.BusinessException businessException, Throwable cause) {
        super(message, cause);
        this.businessException = businessException;
    }

    public common.bss.com.bskyb.BusinessException getFaultInfo() {
        return this.businessException;
    }
}
