package traffic.wcf.bss.com.bskyb.tsversion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-12T12:37:21.039+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion", name = "ITSVersion")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, common.bss.com.bskyb.ObjectFactory.class, aquisition.contract.bss.com.bskyb.ObjectFactory.class, ObjectFactory.class, traffic.contract.bss.com.bskyb.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ITSVersion {

    @WebResult(name = "GetResponse", targetNamespace = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion", partName = "parameters")
    @Action(input = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion/ITSVersion/Get", output = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion/ITSVersion/GetResponse", fault = {@FaultAction(className = ITSVersionGetBusinessExceptionFaultFaultMessage.class, value = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion/ITSVersion/GetBusinessExceptionFault")})
    @WebMethod(operationName = "Get", action = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion/ITSVersion/Get")
    public GetResponse get(
        @WebParam(partName = "parameters", name = "Get", targetNamespace = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion")
        Get parameters
    ) throws ITSVersionGetBusinessExceptionFaultFaultMessage;
}
