package traffic.wcf.bss.com.bskyb.tsversion;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-06-12T12:37:21.075+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "TSVersion", 
                  wsdlLocation = "file:/Users/perrygil/AnypointStudio/workspace/ts-version-connector/src/main/resources/TSVersion.wsdl",
                  targetNamespace = "http://BSkyB.com.BSS.WCF.Traffic/TSVersion") 
public class TSVersion extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://BSkyB.com.BSS.WCF.Traffic/TSVersion", "TSVersion");
    public final static QName BasicHttpBindingITSVersion = new QName("http://BSkyB.com.BSS.WCF.Traffic/TSVersion", "BasicHttpBinding_ITSVersion");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/perrygil/AnypointStudio/workspace/ts-version-connector/src/main/resources/TSVersion.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TSVersion.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/perrygil/AnypointStudio/workspace/ts-version-connector/src/main/resources/TSVersion.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TSVersion(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TSVersion(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TSVersion() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TSVersion(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TSVersion(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TSVersion(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ITSVersion
     */
    @WebEndpoint(name = "BasicHttpBinding_ITSVersion")
    public ITSVersion getBasicHttpBindingITSVersion() {
        return super.getPort(BasicHttpBindingITSVersion, ITSVersion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITSVersion
     */
    @WebEndpoint(name = "BasicHttpBinding_ITSVersion")
    public ITSVersion getBasicHttpBindingITSVersion(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingITSVersion, ITSVersion.class, features);
    }

}
